import type { Metadata } from 'next';
import { Comfortaa } from 'next/font/google';
import './globals.css';
import Header from '@/app/components/Header';

const comfortaa = Comfortaa({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'LOTTOBIT',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} bg-gradient-to-r from-[#F1C017] to-[#C9940A]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
